name: v2-automerge-pandoc
version: 0.1.0.0
github: "githubuser/arisgk"
license: BSD-3-Clause
author: "Aris Goudouras"
maintainer: "aris.gk@gmail.com"
copyright: "2024 Aris Goudouras"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/v2-automerge-pandoc#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - aeson >= 2.1.2.1 && < 2.3
    - text >=2.0.0

executables:
  v2-automerge-pandoc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - v2-automerge-pandoc

tests:
  v2-automerge-pandoc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - v2-automerge-pandoc
