name: automerge-pandoc
version: 0.1.0.0
github: "githubuser/arisgk"
license: GPL-3.0
author: "Aris Goudouras"
maintainer: "aris.gk@gmail.com"
copyright: "2024 Aris Goudouras"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/automerge-pandoc#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - aeson >= 2.2.3.0
    - bytestring >= 0.12.1.0
    - text >= 2.1.1
    - pandoc >= 3.5
    - pandoc-types >= 1.23.1
    - containers >= 0.7
    - mtl >= 2.3.1
  other-modules:
    - Utils.JSON
    - Utils.Sequence

executables:
  automerge-pandoc:
    main: Main.hs
    source-dirs: app
    dependencies:
      - automerge-pandoc
      - bytestring >= 0.12.1.0
      - raw-strings-qq >= 1.1
      - text >= 2.1.1
      - pandoc >= 3.5
      - pandoc-types >= 1.23.1
      - optparse-applicative >= 0.18.1.0

tests:
  automerge-pandoc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - automerge-pandoc
